[manifest]
version = "1.0.0"
priority = 0

[[patches]]
[patches.pattern]
target = "functions/UI_definitions.lua"
pattern = "local use = nil"
position = "after"
payload = '''
use = create_cast_button(card)
'''
match_indent = true
times = 1
